{
  "contest": 269,
  "handle": "wisdomn_",
  "risk": "3",
  "title": "Function emergencyWithdraw is vulnerable to Reentrancy Attack",
  "issueId": 17,
  "issueUrl": "https://github.com/code-423n4/2023-08-goodentry-findings/issues/17"
}